src/DataWarehouse/Models/Web/ToDo/ToDoListViewModel.cs
using DataWarehouse.Common.Data.Model.TractData;
using System;
using System.ComponentModel.DataAnnotations;

namespace DataWarehouse.Models.Web.ToDo
{
    public class ToDoListViewModel
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "List Name")]
        public string Name { get; set; }
        
        [Display(Name = "Description")]
        public string Description { get; set; }

        public ToDoListViewModel() { }

        public ToDoListViewModel(ToDoList todoList)
        {
            Id = todoList.Id;
            Name = todoList.Name;
            Description = todoList.Description;
        }
    }
}

src/DataWarehouse/Controllers/BaseController.cs
using System.Web.Mvc;

namespace DataWarehouse.Controllers
{
    public class BaseController : Controller
    {
        public virtual ActionResult Index()
        {
            return View();
        }
    }
}

src/DataWarehouse/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataWarehouse.Controllers
{
    public class ErrorController : Controller
    {
        //
        // GET: /Error/Index
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/DataWarehouse/Controllers/HomeController.cs
using System.Web.Mvc;
using DataWarehouse.Common.Data;


namespace DataWarehouse.Controllers {
    public class HomeController : BaseController
    {
        private readonly DataWarehouseDbContext _context;

        public HomeController(DataWarehouseDbContext context)
        {
            _context = context;
        }

        public ActionResult Missing()
        {
            return View();
        }

        public ActionResult SidebarPartial()
        {
            return PartialView("_SidebarPartial");
        }
    }
}

src/DataWarehouse/Controllers/ToDoListController.cs
using DataWarehouse.Common.Data;
using DataWarehouse.Common.Data.Repository;
using DataWarehouse.Models.Web.ToDo;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DataWarehouse.Controllers
{
    public class ToDoListController : BaseController
    {
        private DataWarehouseDbContext _context;
        private readonly ToDoListRepository _lookupRepository;

        public ToDoListController(DataWarehouseDbContext context)
        {
            _context = context;
            _lookupRepository = new ToDoListRepository(context);
        }

        private object GetViewModel()
        {
            return _lookupRepository.GetToDoLists().Select(x => new ToDoListViewModel(x)).ToList();
        }

        [ValidateInput(false)]
        public ActionResult GridViewPartial()
        {
            return PartialView("_GridViewPartial", GetViewModel());
        }

        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> GridViewPartialUpdate(ToDoListViewModel item)
        {
            if (ModelState.IsValid)
            {
                if (_lookupRepository.IsDuplicateToDoList(item.Name, item.Id))
                    ModelState.AddModelError("Name", "Duplicated list, list name must be unique");
                else
                    await _lookupRepository.UpdateToDoList(item.Id, item.Name, item.Description);
            }
            else ViewData["EditError"] = "Please, correct all errors.";
            return GridViewPartial();
        }

        [HttpPost, ValidateInput(false)]
        public async Task<ActionResult> GridViewPartialDelete(Guid id)
        {
            if (id != null)
            {
                await _lookupRepository.RemoveToDoList(id);
            }
            return GridViewPartial();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(ToDoListViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_lookupRepository.IsDuplicateToDoList(model.Name, null))
                        ModelState.AddModelError("Name", "Duplicate list, list name must be unique");
                    else
                        await _lookupRepository.AddToDoList(model.Name, model.Description);
                }
            }
            catch (Exception e)
            {
                while (e.InnerException != null) e = e.InnerException;
                ModelState.AddModelError(String.Empty, e.Message);
            }

            return View("Index");
        }
    }
}

src/DataWarehouse/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="PetroBeacon Lighthouse">
    <meta name="author" content="PetroBeacon">
    <meta name="keyword" content="Lighthouse,PetroBeacon,Oil,Gas,Peloton,OpenWells,WellEZ">
    <link rel="shortcut icon" href="~/Images/favicon.png">
    @{
        ViewBag.Title = "Demo App";
    }

    <title>@ViewBag.Title</title>
    


    @Styles.Render("~/Content/css")
    @Html.DevExpress().GetStyleSheets(
        new StyleSheet {ExtensionSuite = ExtensionSuite.NavigationAndLayout},
        new StyleSheet {ExtensionSuite = ExtensionSuite.Editors},
        new StyleSheet {ExtensionSuite = ExtensionSuite.HtmlEditor},
        new StyleSheet {ExtensionSuite = ExtensionSuite.GridView},
        new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList },
        new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        new StyleSheet { ExtensionSuite = ExtensionSuite.SpellChecker }
    )

    @Scripts.Render("~/Scripts/libs/common/jquery/jquery.js")
    @Scripts.Render("~/Scripts/libs/common/jquery/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/libs/common/jquery/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/libs/common/jquery/jquery.countdown.min.js")
    @Scripts.Render("~/Scripts/libs/devexpress/ace.js")
    @Scripts.Render("~/Scripts/libs/common/jquery/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/Scripts/libs/common/jquery/jquery-ui.js")
    @Scripts.Render("~/Scripts/libs/devexpress/knockout-3.4.2.js")
    @Scripts.Render("~/Scripts/libs/devexpress/ext-language_tools.js")
    @Scripts.Render("~/Scripts/libs/devexpress/cldr.js")
    @Scripts.Render("~/Scripts/libs/devexpress/cldr.event.js")
    @Scripts.Render("~/Scripts/libs/devexpress/cldr.supplemental.js")
    @Scripts.Render("~/Scripts/libs/devexpress/globalize.js")
    @Scripts.Render("~/Scripts/libs/devexpress/globalize.message.js")
    @Scripts.Render("~/Scripts/libs/devexpress/globalize.number.js")
    @Scripts.Render("~/Scripts/libs/devexpress/globalize.date.js")
    @Scripts.Render("~/Scripts/libs/devexpress/globalize.currency.js")
    @Scripts.Render("~/Scripts/libs/template/tether.min.js")
    @Scripts.Render("~/Scripts/libs/template/bootstrap.min.js")
    @Scripts.Render("~/Scripts/libs/template/pace.min.js")
    @Scripts.Render("~/Scripts/libs/jquery.signalR-2.2.2.min.js")


    <!-- Google Analytics -->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-108393344-1', 'auto');
        //if (location.hostname === 'localhost') {
        //    ga('set', 'sendHitTask', null);


        ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->


    @Html.DevExpress().GetScripts(
    new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
    new Script { ExtensionSuite = ExtensionSuite.GridView },
    new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
    new Script { ExtensionSuite = ExtensionSuite.Editors },
    new Script { ExtensionSuite = ExtensionSuite.Chart },
    new Script { ExtensionSuite = ExtensionSuite.TreeList }
)
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">

    <header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler hidden-lg-up" style="color: white" type="button">&#9776;</button>
        <ul class="nav navbar-nav hidden-md-down float-left">
            <li class="nav-item">
                <a class="nav-link navbar-toggler sidebar-toggler" href="#">&#9776;</a>
            </li>
        </ul>
        <h5 style="text-align: center; position: fixed; margin-top: 10px; left: 45%; color: white; z-index: -1">Demo App</h5>
    </header>
    <div class="app-body">
        @Html.Action("SidebarPartial")
        <!-- Main content -->
        <main class="main">
            @Html.Partial("_BreadcrumbPartial")
            <div class="container-fluid">
                <div id="ui-view"></div>
                @Html.DevExpress().LoadingPanel(settings =>
                {
                    settings.Name = "LoadingPanel";
                    settings.Modal = true;
                    settings.ContainerElementID = "";
                    settings.Text = "Loading...";
                }).GetHtml()
            </div>
        </main>
    </div>

    <!-- GenesisUI main scripts -->
    <script src="~/Scripts/app.js?v1.10"></script>

    <script type="text/javascript">
        var nextNotificationId = 0;
        var notificationCount = 0;
        var notification = [];

        $(document).ready(function () {

            // Init SignalR
            var client = $.connection.informationHub;
            if (client) {
                client.client.addNotification = function (message, icon, textType) {
                    if (notificationCount == 0) {
                        var $bell = $('<span id="notification_info" class="badge badge-pill badge-danger notification_count">0</span>');
                        $("#notification_bell").append($bell);
                    }
                    notificationCount++;
                    $('.notification_count').each(function () {
                        $(this).text(notificationCount);
                    });
                    if (textType == null) textType = "text-info";
                    if (icon == null) icon = "icon-info";
                    var $element = $('<a href="#" class="dropdown-item" onclick="handleNotification(this.id);"><i class="' + icon + ' ' + textType + '"></i> ' + message + '</a>');
                    $element.attr("id", "notification_" + nextNotificationId);
                    $element.insertAfter($("#notification_list"));
                    notification.push($element);

                    nextNotificationId++;
                };

                //ping pong with the server, the server can return 401 code
                client.client.ping = function () {
                    $.connection.informationHub.server.ping();
                };

                // Start the connection.
                $.connection.hub.start().done(function () {
                    //We are connected to the information hub
                });
            }

                // set return url for change password view
            $('#changePassword').one('click', function (e) {
                //e.preventDefault();
                this.href = this.href + "&ReturnUrl=%2F%23" + window.location.hash.substring(1);;;
                //$(this).click();
            });

            console.log(window.location.href);
        });

        function clearNotifications() {
            $("#notification_info").remove();
            notification.forEach(function (element, index, array) {
                element.remove();
            });
            notification = [];
            notificationCount = 0;
            $('.notification_count').each(function () {
                $(this).text(notificationCount);
            });
        }

        function handleNotification(id) {
            $("#" + id).remove();
            notificationCount--;
            if (notificationCount == 0) {
                $("#notification_info").remove();
            }
            $('.notification_count').each(function () {
                $(this).text(notificationCount);
            });
        }

        MVCxClientGlobalEvents.AddCallbackErrorHandler(function (s, e) {
            // do not show an error message in devexpress controls if server returns 401 code - it means session is expired
            var re = /401[\.\d\s-]*Unauthorized/;
            if (re.test(e.message))
                e.handled = true;
        });

        MVCxClientGlobalEvents.AddControlsInitializedEventHandler(function (s, e) {
            if ($.initPageLoaded)
                return;

            // Set url
            setTimeout(function () {
                $.initPageLoaded = true;
                var hash = location.hash;
                if (sessionStorage.getItem("currentPage")) {
                    hash = sessionStorage.getItem("currentPage");
                    sessionStorage.removeItem("currentPage");
                }
                var url = hash.replace(/^#/, '');
                if (url !== '' && !/.*missing.*/i.test(url)) {
                    setUpUrl(url);
                } else {
                    setUpUrl($.defaultPage);
                }
            }, 100);
        });
        MVCxClientGlobalEvents.AddControlsInitializedEventHandler(InitalizejQuery);

        function InitalizejQuery() {
            $('.draggable').draggable({
                helper: 'clone',    
                start: function (ev, ui) {
                    var $draggingElement = $(ui.helper);
                    $draggingElement.width(GridViewFields.GetWidth());
                },
                cursor: "move"
            });
            $('.draggable').droppable({
                activeClass: "hover",
                tolerance: "intersect",
                hoverClass: "activeHover",
                drop: function (event, ui) {
                    var draggingSortIndex = ui.draggable.attr("visibleIndex");
                    var targetSortIndex = $(this).attr("visibleIndex");
                    if (draggingSortIndex != targetSortIndex) {
                        GridViewFields.PerformCallback(
                        {
                            draggingIndex: draggingSortIndex,
                            targetIndex: targetSortIndex,
                            command: "DRAGROW"
                            });
                    }
                }
            });
        }
    </script>
</body>
</html>

src/DataWarehouse/Views/Home/Missing.cshtml
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="clearfix">
                <h1 class="float-left display-3 mr-2">404</h1>
                <h4 class="pt-1">Oops! You're lost.</h4>
                <p class="text-muted">The page you are looking for was not found.</p>
            </div>
        </div>
    </div>
</div>

src/DataWarehouse/Views/Home/_BreadcrumbPartial.cshtml
<ol id="breadcrumb" class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
</ol>

src/DataWarehouse/Views/Home/_SidebarPartial.cshtml
@using System.Security.Claims
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="ToDoList/Index"><i class="icon-doc"></i> ToDo Lists</a>
            </li>
        </ul>
    </nav>
</div>

src/DataWarehouse/Views/ToDoList/Index.cshtml
@using System.Web.Mvc.Html
@using System.Web.UI.WebControls
@model DataWarehouse.Models.Web.ToDo.ToDoListViewModel

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="icon-people"></i>ToDo Lists
            </div>
            <div style="padding: 5px;" class="card-block" id="container">
                @Html.Action("GridViewPartial")
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<!--/.row-->

<div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <i class="icon-user-follow"></i>Create List
            </div>
            <div class="card-block">
                @using (Html.BeginForm("Index", "ToDoList", FormMethod.Post, new { @id = "createListForm" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                @Html.DevExpress().LabelFor(x => x.Name, s => s.Text = "List Name").GetHtml()
                                @Html.DevExpress().TextBoxFor(x => x.Name, s =>
                                {
                                    s.Properties.NullText = "Enter Name";
                                    s.ShowModelErrors = true;
                                    s.Properties.ValidationSettings.Display = Display.Dynamic;
                                    s.Width = Unit.Percentage(100);
                                }).GetHtml()
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <div class="form-group">
                                @Html.DevExpress().LabelFor(x => x.Description, s => s.Text = "Description").GetHtml()
                                @Html.DevExpress().TextBoxFor(x => x.Description, s =>
                                {
                                    s.Properties.NullText = "Enter Description";
                                    s.ShowModelErrors = true;
                                    s.Properties.ValidationSettings.Display = Display.Dynamic;
                                    s.Width = Unit.Percentage(100);
                                }).GetHtml()
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                @Html.DevExpress().Button(s =>
                                {
                                    s.Name = "btnSubmit";
                                    s.Text = "Add New List";
                                    s.UseSubmitBehavior = true;
                                }).GetHtml()
                            </div>
                        </div>
                    </div>
                    @Html.DevExpress().ValidationSummary().GetHtml()
                    @Html.ValidationSummary(true, null, new { @class = "dxvsValidationSummary_DevEx" })
                }
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<script type="text/javascript">
    $("#createListForm").submit(function (e) {
        e.preventDefault();
        submitForm("ToDoList/Index", "POST", "createListForm");
    });
</script>

src/DataWarehouse/Views/ToDoList/_GridViewPartial.cshtml
@using System.Web.UI.WebControls
@using DevExpress.Data
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        const string controllerName = "ToDoList";

        settings.Name = "GridView";
        settings.CallbackRouteValues = new { Controller = controllerName, Action = "GridViewPartial" };

        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = controllerName, Action = "GridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = controllerName, Action = "GridViewPartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsText.ConfirmDelete = "Are you sure you want to delete this list?";
        settings.Width = Unit.Percentage(100);
        settings.SettingsPager.Mode = GridViewPagerMode.EndlessPaging;
        settings.Styles.AlternatingRow.Enabled = DefaultBoolean.True;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.LightCyan;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;
        settings.CommandColumn.VisibleIndex = 9;
        settings.CommandColumn.Caption = "Actions";
        settings.CommandColumn.Width = Unit.Pixel(90);

        settings.KeyFieldName = "Id";
        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowHeaderFilterButton = true;
        settings.SettingsBehavior.AllowSelectByRowClick = false;
        settings.SettingsBehavior.AllowFocusedRow = false;

        settings.Columns.Add(column =>
        {
            column.FieldName = "Id";
            column.Caption = "Id";
            column.Visible = false;
        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "Name";
            column.Caption = "Name";
            column.ReadOnly = false;
            column.SortOrder = ColumnSortOrder.Ascending;
            column.Width = Unit.Percentage(72);
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "Description";
            column.Caption = "Description";
            column.ReadOnly = false;
            column.SortOrder = ColumnSortOrder.Ascending;
            column.Width = Unit.Percentage(72);
        });

        if (ViewData["EditError"] != null)
        {
            settings.Settings.ShowFooter = !Convert.ToBoolean(ViewData["IsEditing"]);
            settings.SetFooterRowTemplateContent(c => {
                Html.ViewContext.Writer.Write(@"<span class=""dxgvEditingErrorRow_DevEx"">{0}</span>", ViewData["EditError"]);
            });
        }

        settings.BeforeGetCallbackResult = (s, e) =>
        {
            if(ViewData["EditError"] != null && !Convert.ToBoolean(ViewData["IsEditing"]))
            {
                MVCxGridView gridView = (MVCxGridView)s;
                gridView.Settings.ShowFooter = true;
            }
        };
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()